app:
  otel_metrics_enabled: false
  otel_metrics_port: 9464
  otel_traces_enabled: false
  otel_traces_port: 4317

# core:
#   service_name: ServiceManager
#   net:
#     sm_discovery: UdpDiscovery
#     tcp_address: 0.0.0.0
#     tcp_port: 0
#     udp_address: 0.0.0.0
#     udp_port: 5707
#   retry:
#     backoff:
#       enable: false
#       max_delay: 240000
#       multiplier: 2
#     interval: 2000
#     max_try: 0

log:
  log_level: silly
#   format: console
#   max_files: 14d
#   max_size: 20m
